#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build x86_64 Project OpenWrt

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - 'config/x86_64-project-openwrt.config'
  schedule:
    - cron: 0 18 * * *
#  watch:
#    types: [started]

env:
  REPO_URL: https://github.com/project-openwrt/openwrt
  REPO_BRANCH: 18.06-kernel5.4
  CONFIG_FILE: config/x86_64-project-openwrt.config
  DIY_SH: scripts/lean-openwrt.sh
  TZ: Asia/Shanghai
  TARGET: x86
  SUBTARGET: 64
  DEVICE: openwrt-x86-64
  SSH_ACTIONS: false
  UPLOAD_WETRANSFER: true
  UPLOAD_COWTRANSFER: true


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /swapfile
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler gperf antlr3
        curl -fsSL https://raw.githubusercontent.com/P3TERX/dotfiles/master/.bashrc >> ~/.bashrc

    - name: Clone Source Code
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update Feeds
      run: |
       cd openwrt
       ./scripts/feeds update -a

    - name: Install Feeds
      run: cd openwrt && ./scripts/feeds install -a
      
    - name: Load Custom Configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        make defconfig

    - name: Bind Folders
      run: |
        cd openwrt
        mkdir -p bin/targets/$TARGET/$SUBTARGET/packages
        mkdir -p files/www/snapshots/targets/$TARGET/$SUBTARGET/packages
        sudo mount --bind bin/targets/$TARGET/$SUBTARGET/packages files/www/snapshots/targets/$TARGET/$SUBTARGET/packages
        cp scripts/ipkg-make-index.sh files/www/snapshots
        sed -i "s/.*sha256sum=.*/\tsha256sum=$\(sha256sum \$pkg \| awk '{ print \$1 }'\)"/g files/www/snapshots/ipkg-make-index.sh
        
    - name: SSH Connection To Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Download Package
      id: package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile The Firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) IGNORE_ERRORS=1 || make -j1 V=s IGNORE_ERRORS=1
        echo "::set-output name=status::success"
        
    - name: Arrange Packages
      if: steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin
        mkdir -p targets/$TARGET/$SUBTARGET/pre-snapshots/snapshots
        mkdir -p targets/$TARGET/$SUBTARGET/pre-snapshots/snapshots/targets/$TARGET/$SUBTARGET
        cp -r packages targets/$TARGET/$SUBTARGET/pre-snapshots/snapshots
        cp -r targets/$TARGET/$SUBTARGET/packages targets/$TARGET/$SUBTARGET/pre-snapshots/snapshots/targets/$TARGET/$SUBTARGET
        zip -q -r targets/$TARGET/$SUBTARGET/packages.zip targets/$TARGET/$SUBTARGET/pre-snapshots/snapshots
        mkdir -p targets/$TARGET/$SUBTARGET/pre-packages-server
        cp -r ../../server targets/$TARGET/$SUBTARGET/pre-packages-server
        cd targets/$TARGET/$SUBTARGET
        cp -r pre-snapshots/snapshots pre-packages-server/server/web
        zip -q -r packages-server.zip pre-packages-server/server
        
    - name: Upload Config
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: config.seed
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/config.seed
        
    - name: Upload Packages
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: packages
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/pre-snapshots
        
    - name: Upload Packages-Server
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: packages-server
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/pre-packages-server
        
    - name: Upload Packages Info
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-generic.manifest
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-generic.manifest
        
    - name: Upload Kernel Packages
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: kernel-packages
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/packages/
        
    - name: Upload RootFS Archive
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-generic-rootfs.tar.gz
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-generic-rootfs.tar.gz

    - name: Upload Generic SquashFS Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-rootfs-squashfs.img
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-rootfs-squashfs.img

    - name: Upload Combined DVD Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-combined-squashfs.img
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-combined-squashfs.img
        
    - name: Upload Combined PVE/KVM Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-combined-squashfs.qcow2
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-combined-squashfs.qcow2
        
    - name: Upload Combined VirtualBox Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-combined-squashfs.vdi
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-combined-squashfs.vdi
        
    - name: Upload Combined VMware Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-combined-squashfs.vmdk
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-combined-squashfs.vmdk
        
    - name: Upload Combined Hyper-V Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-combined-squashfs.vhdx
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-combined-squashfs.vhdx

    - name: Upload GPT DVD Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-uefi-gpt-squashfs.img
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-uefi-gpt-squashfs.img
        
    - name: Upload GPT PVE/KVM Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-uefi-gpt-squashfs.qcow2
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-uefi-gpt-squashfs.qcow2
        
    - name: Upload GPT VirtualBox Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-uefi-gpt-squashfs.vdi
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-uefi-gpt-squashfs.vdi
        
    - name: Upload GPT VMware Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-uefi-gpt-squashfs.vmdk
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-uefi-gpt-squashfs.vmdk
        
    - name: Upload GPT Hyper-V Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-uefi-gpt-squashfs.vhdx
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-uefi-gpt-squashfs.vhdx

    - name: Upload Images Sha256sums
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: sha256sums
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/sha256sums

    - name: Organize Files
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/$TARGET/$SUBTARGET
        gzip *.img
        rm -rf packages pre-packages-server pre-snapshots
        rm -f *.img
        cd ..
        mkdir -p uefi-images
        mkdir -p legacy-images
        mkdir -p other-files
        mv $SUBTARGET/*gpt* uefi-images
        mv $SUBTARGET/*combined* legacy-images
        mv $SUBTARGET/* other-files
        curl -fsSL git.io/file-transfer | sh
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"
        
    - name: Upload Uefi Firmwares To Cowtransfer
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true'
      run: |
        cd openwrt/bin/targets/$TARGET
        ./transfer cow --block 2621440 -s -p 99 -t 3 --hash --no-progress ./uefi-images 2>&1 | tee cowtransfer-uefi.log
        echo "::warning file=cowtransfer-uefi::$(cat cowtransfer-uefi.log | grep https)"

    - name: Upload Legacy Firmwares To Cowtransfer
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true'
      run: |
        cd openwrt/bin/targets/$TARGET/
        ./transfer cow --block 2621440 -s -p 99 -t 3 --hash --no-progress ./legacy-images 2>&1 | tee cowtransfer-legacy.log
        echo "::warning file=cowtransfer-legacy::$(cat cowtransfer-legacy.log | grep https)"
        
    - name: Upload Other Files To Cowtransfer
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true'
      run: |
        cd openwrt/bin/targets/$TARGET/
        ./transfer cow --block 2621440 -s -p 99 -t 3 --hash --no-progress ./other-files 2>&1 | tee cowtransfer-other.log
        echo "::warning file=cowtransfer-other::$(cat cowtransfer-other.log | grep https)"
        
    - name: Upload Uefi Firmwares To WeTransfer
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true'
      run: |
        cd openwrt/bin/targets/$TARGET
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer-uefi.log
        echo "::warning file=wetransfer-uefi::$(cat wetransfer-uefi.log | grep https)"

    - name: Upload Legacy Firmwares To WeTransfer
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true'
      run: |
        cd openwrt/bin/targets/$TARGET/
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer-legacy.log
        echo "::warning file=wetransfer-legacy::$(cat wetransfer-legacy.log | grep https)"
        
    - name: Upload Other Files To WeTransfer
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true'
      run: |
        cd openwrt/bin/targets/$TARGET/
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer-other.log
        echo "::warning file=wetransfer-other::$(cat wetransfer-other.log | grep https)"
